### ISSUE TITLE
RuntimeError: CUDA error: device-side assert triggered

### ISSUE THREAD

**Issue by Saarraaaah** [Finspire13/RL-Surgical-Gesture-Segmentation#2]
I keep getting this issue when I run 
`
python3 experiment.py`

```
EncoderDecoderNet(
  (encoder): Encoder(
    (module): Sequential(
      (conv_0): Conv1d(14, 64, kernel_size=(51,), stride=(1,), padding=(25,))
      (cn_0): ChannelNorm()
      (relu_0): ReLU()
      (pool_0): MaxPool1d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
      (conv_1): Conv1d(64, 96, kernel_size=(51,), stride=(1,), padding=(25,))
      (cn_1): ChannelNorm()
      (relu_1): ReLU()
      (pool_1): MaxPool1d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
      (conv_2): Conv1d(96, 128, kernel_size=(51,), stride=(1,), padding=(25,))
      (cn_2): ChannelNorm()
      (relu_2): ReLU()
      (pool_2): MaxPool1d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    )
  )
  (decoder): Decoder(
    (module): Sequential(
      (up_0): Upsample(scale_factor=2, mode=nearest)
      (conv_0): ConvTranspose1d(128, 96, kernel_size=(51,), stride=(1,), padding=(25,))
      (cn_0): ChannelNorm()
      (relu_0): ReLU()
      (up_1): Upsample(scale_factor=2, mode=nearest)
      (conv_1): ConvTranspose1d(96, 64, kernel_size=(51,), stride=(1,), padding=(25,))
      (cn_1): ChannelNorm()
      (relu_1): ReLU()
      (up_2): Upsample(scale_factor=2, mode=nearest)
      (conv_2): ConvTranspose1d(64, 64, kernel_size=(51,), stride=(1,), padding=(25,))
      (cn_2): ChannelNorm()
      (relu_2): ReLU()
    )
  )
  (fc1): Linear(in_features=64, out_features=32, bias=True)
  (fc2): Linear(in_features=32, out_features=6, bias=True)
)
0
/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/torch/nn/modules/upsampling.py:129: UserWarning: nn.Upsample is deprecated. Use nn.functional.interpolate instead.
  warnings.warn("nn.{} is deprecated. Use nn.functional.interpolate instead.".format(self.name))
Traceback (most recent call last):
  File "tcn_main.py", line 74, in <module>
    main()
  File "tcn_main.py", line 56, in main
    naming)  #8x6
  File "/home/ubuntu/RL-Surgical-Gesture-Segmentation-master/tcn_train_test.py", line 239, in cross_validate
    log_dir=log_dir)
  File "/home/ubuntu/RL-Surgical-Gesture-Segmentation-master/tcn_train_test.py", line 69, in train_model
    loss.backward()
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/torch/tensor.py", line 102, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/torch/autograd/__init__.py", line 90, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: CUDA error: device-side assert triggered
Traceback (most recent call last):
  File "experiment.py", line 176, in <module>
    main()
  File "experiment.py", line 171, in main
    experiment_tcn()
  File "experiment.py", line 45, in experiment_tcn
    tcn_result[tcn_run_idx-1,:,:] = np.load(run_result_file)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/numpy/lib/npyio.py", line 372, in load
    fid = open(file, "rb")
FileNotFoundError: [Errno 2] No such file or directory: './result/JIGSAWS_K/tcn_result_sensor_run_1.npy'


```
Please help

**Comment by Finspire13** [comment]
Any further information?
@Saarraaaah 

Maybe the problem is that feature files for 'Suturing' are put into the 'Knot Tying' folder. Please be careful with the naming rule.
